# BASIC TENSORFLOW

# LOAD PACKAGES

In [1]:
import numpy as np
import tensorflow as tf
print ("PACKAGES LOADED")

PACKAGES LOADED


# Defining Tensors

In [2]:
m1 = [[1.0, 2.0], 
      [3.0, 4.0]]
m2 = np.array([[1.0, 2.0],
              [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

In [3]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [4]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [5]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


# SESSION

In [6]:
sess = tf.Session()
print ("OPEN SESSION")

OPEN SESSION


# TF CONSTANT

In [7]:
def print_tf(x):
    print("TYPE IS\n %s" % (type(x)))
    print("VALUE IS\n %s" % (x))
hello = tf.constant("HELLO. IT'S ME. ")
print_tf(hello)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_3:0", shape=(), dtype=string)


# TO MAKE THINKS HAPPEN

In [8]:
hello_out = sess.run(hello)
print_tf(hello_out)

TYPE IS
 <class 'bytes'>
VALUE IS
 b"HELLO. IT'S ME. "


# OTHER TYPES OF CONSTANTS

In [9]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_4:0", shape=(), dtype=float32)
TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_5:0", shape=(), dtype=float32)


In [10]:
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 1.5
TYPE IS
 <class 'numpy.float32'>
VALUE IS
 2.5


# OPERATORS

In [11]:
a_plus_b = tf.add(a, b)
print_tf(a_plus_b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Add:0", shape=(), dtype=float32)


In [12]:
a_plus_b_out = sess.run(a_plus_b)
print_tf(a_plus_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 4.0


In [13]:
a_mul_b = tf.multiply(a, b)
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 3.75


# VARIABLES

In [14]:
weight = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight)

TYPE IS
 <class 'tensorflow.python.ops.variables.Variable'>
VALUE IS
 <tf.Variable 'Variable:0' shape=(5, 2) dtype=float32_ref>


In [15]:
weight_out = sess.run(weight)
print_tf(weight_out)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: Variable/_8 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_4_Variable", _device="/job:localhost/replica:0/task:0/gpu:0"](Variable)]]
	 [[Node: Variable/_9 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_4_Variable", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

# WHY DOES THIS ERROR OCCURS?

In [16]:
init = tf.global_variables_initializer()
sess.run(init)
print ("INITIALIZING ALL VARIALBES")

INITIALIZING ALL VARIALBES


# ONCE, WE INITIALIZE VARIABLES

In [17]:
weight_out = sess.run(weight)
print_tf(weight_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.00813493  0.16322781]
 [-0.07509127  0.01595697]
 [-0.07316905 -0.02729499]
 [-0.10284281 -0.00276054]
 [-0.04249415  0.0470983 ]]


# PLACEHOLDERS

In [18]:
x = tf.placeholder(tf.float32, [None, 5])
print_tf(x)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


## OPERATION WITH VARIABLES AND PLACEHOLDERS

In [19]:
oper = tf.matmul(x, weight)
print_tf(oper)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("MatMul:0", shape=(?, 2), dtype=float32)


In [20]:
data = np.random.rand(1, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.13978612  0.04058734]]


In [21]:
data = np.random.rand(2, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.12024556  0.14268856]
 [-0.14612302  0.02197018]]


In [22]:
sess.close()